#!/bin/bash


convert ol.png dr.png tc.png tm.png ts.png \
-compose Multiply \
\( -clone 0 -fill black -draw "color 0,0 Floodfill" -negate -clone 0 -composite -negate \) -swap 0 +delete \
\( -clone 0         -clone 1 -composite                     \) -swap 0 +delete -delete 1 \
\( -clone 1 -negate -clone 0 -composite                     \) -swap 1 +delete \
\( -clone 2         -clone 0 -composite -clone 1 -composite \) -swap 2 +delete \
\( -clone 3 -negate -clone 0 -composite                     \) -swap 3 +delete \
-alpha Copy \
\( -clone 0 -blur 8,2  -shade 120x30 \( -clone 0 -alpha Opaque -sparse-color barycentric "0,0 #202020 %w,%h #101010" \) -compose Overlay -composite -clone 0 -compose CopyOpacity -composite \) -swap 0 +delete \
\( -clone 1 -blur 16,4 -shade 120x30 \( -clone 0 -alpha Opaque -sparse-color barycentric "0,0 #EEB300 %w,%h #DDA000" \) -compose Overlay -composite -clone 1 -compose CopyOpacity -composite \) -swap 1 +delete \
\( -clone 2 -blur 16,4 -shade 120x30 \( -clone 0 -alpha Opaque -sparse-color barycentric "0,0 #404040 %w,%h #202020" \) -compose Overlay -composite -clone 2 -compose CopyOpacity -composite \) -swap 2 +delete \
\(                                      -clone 3 -alpha Opaque -sparse-color barycentric "0,0 #FFFFFF %w,%h #E6E6E6"                                -clone 3 -compose CopyOpacity -composite \) -swap 3 +delete \
-compose Over \
\( -clone 0 -clone 1 -composite -clone 2 -composite -clone 3 -composite -bordercolor Transparent -border 160 \) -insert 0 -delete 1--1 \
\( -clone 0 -alpha Opaque -sparse-color barycentric "0,0 grey50 0,%h black" -clone 0 -composite \) -insert 0 -delete 1--1 \
-scale 25% top.png


convert ol.png dr.png bc.png bm.png bs.png \
-flop -compose Multiply \
\( -clone 0 -fill black -draw "color 0,0 Floodfill" -negate -clone 0 -composite -negate \) -swap 0 +delete \
\( -clone 0         -clone 1 -composite                     \) -swap 0 +delete -delete 1 \
\( -clone 1 -negate -clone 0 -composite                     \) -swap 1 +delete \
\( -clone 2         -clone 0 -composite -clone 1 -composite \) -swap 2 +delete \
\( -clone 3 -negate -clone 0 -composite                     \) -swap 3 +delete \
-alpha Copy \
\( -clone 0 -blur 8,2  -shade 120x30 \( -clone 0 -alpha Opaque -sparse-color barycentric "0,0 #202020 %w,%h #101010" \) -compose Overlay -composite -clone 0 -compose CopyOpacity -composite \) -swap 0 +delete \
\( -clone 1 -blur 16,4 -shade 120x30 \( -clone 0 -alpha Opaque -sparse-color barycentric "0,0 #EEB300 %w,%h #DDA000" \) -compose Overlay -composite -clone 1 -compose CopyOpacity -composite \) -swap 1 +delete \
\( -clone 2 -blur 16,4 -shade 120x30 \( -clone 0 -alpha Opaque -sparse-color barycentric "0,0 #404040 %w,%h #202020" \) -compose Overlay -composite -clone 2 -compose CopyOpacity -composite \) -swap 2 +delete \
\(                                      -clone 3 -alpha Opaque -sparse-color barycentric "0,0 #FFFFFF %w,%h #E6E6E6"                                -clone 3 -compose CopyOpacity -composite \) -swap 3 +delete \
-compose Over \
\( -clone 0 -clone 1 -composite -clone 2 -composite -clone 3 -composite -bordercolor Transparent -border 160 \) -insert 0 -delete 1--1 \
\( -clone 0 -alpha Opaque -sparse-color barycentric "0,0 grey50 0,%h black" -clone 0 -composite \) -insert 0 -delete 1--1 \
-scale 25% bottom.png


rm ol.png dr.png tc.png bc.png tm.png bm.png ts.png bs.png
